export const lkpGenderIds=[ {"id": "52392", "name": "Female"},
        {"id": "52393", "name": "Male"}];
export const lstAgeRange=[  {"id": "1", "name": "2 years old and less"},                
	   {"id": "2", "name": "More than 2 years old"}];
export const lkpIncidentTypeIds=[   {"id": "52121", "name": "Death"},
        {"id": "52122", "name": "Serious Injury"},
        {"id": "52123", "name": "Injury"},
        {"id": "52124", "name": "Product Defect"},
        {"id": "52125", "name": "Incorrect/Insufficient Information"},
        {"id": "52126", "name": "Recall"},
        {"id": "52127", "name": "Property Damage"},
        {"id": "52128", "name": "Incident, No Injury"},
        {"id": "52129", "name": "Other"}];
export const lkpInjuryTypeIds=[ {"id": "52135", "name": "No Injury"},
        {"id": "52136", "name": "Amputation"},
        {"id": "52138", "name": "Bruise/Abrasion/Contusion/Pinching"},
        {"id": "52139", "name": "Burn/Scald"},
        {"id": "52151", "name": "Choking"},
        {"id": "52140", "name": "Concussion"},
        {"id": "52141", "name": "Cut/Laceration"},
        {"id": "52144", "name": "Dislocation"},
        {"id": "52145", "name": "Drowning"},
        {"id": "52146", "name": "Electric Shock"},
        {"id": "52137", "name": "Fracture"},
        {"id": "511050", "name": "Inflammation/Irritation/Dermatitis"},
        {"id": "52152", "name": "Ingested Object"},
        {"id": "52148", "name": "Internal Organ Injury"},
        {"id": "52147", "name": "Piercing/puncturing/penetration"},
        {"id": "52153", "name": "Poisoning"},
        {"id": "52157", "name": "Strain / Sprain"},
        {"id": "52149", "name": "Strangulation"},
        {"id": "511051", "name": "Suffocation"},
        {"id": "52158", "name": "Other/Not Stated"}];
export const lkpTreatmentTypeIds=[ {"id": "52299", "name": "None"},
        {"id": "52300", "name": "First Aid"},
        {"id": "52301", "name": "Provincial Health Care Info Service"},
        {"id": "52302", "name": "Poison Control Centre"},
        {"id": "52303", "name": "Family Doctor"},
        {"id": "52304", "name": "Hospital-Emergency Room"},
        {"id": "52305", "name": "Hospital-Other"},
        {"id": "52306", "name": "Other Medical Professional"},
        {"id": "52307", "name": "Other"},
        {"id": "52308", "name": "Unknown"}];
export const lkpBodyPartIds=[ {"id": "51581", "name": "25-50% of body"},
        {"id": "51582", "name": "All parts of the body"},
        {"id": "51583", "name": "Ankle"},
        {"id": "51584", "name": "Arm"},
        {"id": "51585", "name": "Ear"},
        {"id": "51586", "name": "Elbow"},
        {"id": "51587", "name": "Eyeball"},
        {"id": "51588", "name": "Face (including eyelid, eye area and nose)"},
        {"id": "51589", "name": "Finger"},
        {"id": "51590", "name": "Foot"},
        {"id": "51591", "name": "Hand"},
        {"id": "51592", "name": "Internal (use with aspiration and ingestion)"},
        {"id": "51593", "name": "Knee"},
        {"id": "51594", "name": "Leg"},
        {"id": "51595", "name": "Mouth"},
        {"id": "51596", "name": "Neck"},
        {"id": "51598", "name": "Pubic Region"},
        {"id": "51599", "name": "Shoulder (including clavicle, collarbone)"},
        {"id": "51600", "name": "Toe"},
        {"id": "51601", "name": "Trunk"},
        {"id": "51602", "name": "Wrist"},
        {"id": "51597", "name": "Not Recorded"}];
