  export const lstCountries=[
	      {"id": "Canada", "name": "Canada"},                
	      {"id": "United States", "name": "United States"},
	      {"id": "Other", "name": "Other"}
	    ]
export const lstProvinces= [
	      {"id": "Alberta", "name": "Alberta"},                
	      {"id": "British Columbia", "name": "British Columbia"},
	      {"id": "Manitoba", "name": "Manitoba"},
	      {"id": "New Brunswick", "name": "New Brunswick"},
	      {"id": "Newfoundland and Labrador", "name": "Newfoundland and Labrador"},
	      {"id": "Northwest Territories", "name": "Northwest Territories"},
	      {"id": "Nova Scotia", "name": "Nova Scotia"},
	      {"id": "Nunavut", "name": "Nunavut"},
	      {"id": "Ontario", "name": "Ontario"},
	      {"id": "Prince Edward Island", "name": "Prince Edward Island"},
	      {"id": "Quebec", "name": "Quebec"},
	      {"id": "Saskatchewan", "name": "Saskatchewan"},           
	      {"id": "Yukon", "name": "Yukon"}
	    ]
export const lstStates=[
	      {"id": "Alabama", "name": "Alabama"},                
	      {"id": "Alaska", "name": "Alaska"},
	      {"id": "American Samoa", "name": "American Samoa"},
	      {"id": "Arizona", "name": "Arizona"},	      
	      {"id": "Arkansas", "name": "Arkansas"},
	      {"id": "California", "name": "California"},
	      {"id": "Colorado", "name": "Colorado"},
	      {"id": "Connecticut", "name": "Connecticut"},
	      {"id": "Delaware", "name": "Delaware"},
	      {"id": "District of Columbia", "name": "District of Columbia"},
	      {"id": "Federated States of Micronesia", "name": "Federated States of Micronesia"},
	      {"id": "Florida", "name": "Florida"},
	      {"id": "Georgia", "name": "Georgia"},
	      {"id": "Guam", "name": "Guam"},
	      {"id": "Hawaii", "name": "Hawaii"},
	      {"id": "Idaho", "name": "Idaho"},
	      {"id": "Illinois", "name": "Illinois"},           
	      {"id": "Indiana", "name": "Indiana"},
	      {"id": "Iowa", "name": "Iowa"},
	      {"id": "Kansas", "name": "Kansas"},
	      {"id": "Kentucky", "name": "Kentucky"},
	      {"id": "Louisiana", "name": "Louisiana"},
	      {"id": "Maine", "name": "Maine"},
	      {"id": "Marshall Islands", "name": "Marshall Islands"},
	      {"id": "Maryland", "name": "Maryland"},
	      {"id": "Massachusetts", "name": "Massachusetts"},
	      {"id": "Michigan", "name": "Michigan"},
	      {"id": "Minnesota", "name": "Minnesota"},
	      {"id": "Mississippi", "name": "Mississippi"},
	      {"id": "Missouri", "name": "Missouri"},
	      {"id": "Montana", "name": "Montana"},
	      {"id": "Nebraska", "name": "Nebraska"},
	      {"id": "Nevada", "name": "Nevada"},
	      {"id": "New Hampshire", "name": "New Hampshire"},
	      {"id": "New Jersey", "name": "New Jersey"},           
	      {"id": "New Mexico", "name": "New Mexico"},
	      {"id": "New York", "name": "New York"},
	      {"id": "North Carolina", "name": "North Carolina"},
	      {"id": "North Dakota", "name": "North Dakota"},
	      {"id": "Northern Mariana Islands", "name": "Northern Mariana Islands"},
	      {"id": "Ohio", "name": "Ohio"},
	      {"id": "Oklahoma", "name": "Oklahoma"},
	      {"id": "Oregon", "name": "Oregon"},
	      {"id": "Palau", "name": "Palau"},
	      {"id": "Pennsylvania", "name": "Pennsylvania"},
	      {"id": "Puerto Rico", "name": "Puerto Rico"},
	      {"id": "Rhode Island", "name": "Rhode Island"},
	      {"id": "South Carolina", "name": "South Carolina"},
	      {"id": "South Dakota", "name": "South Dakota"},
	      {"id": "Tennessee", "name": "Tennessee"},
	      {"id": "Texas", "name": "Texas"},
	      {"id": "Utah", "name": "Utah"},
	      {"id": "Vermont", "name": "Vermont"},
	      {"id": "Virgin Islands", "name": "Virgin Islands"},
	      {"id": "Virginia", "name": "Virginia"},
	      {"id": "Washington", "name": "Washington"},
	      {"id": "West Virginia", "name": "West Virginia"},
	      {"id": "Wisconsin", "name": "Wisconsin"},
	      {"id": "Wyoming", "name": "Wyoming"}
      ]