export const lkpInfoResourceTypeIds=[{"id": "52023", "name": "Correspondence"}, 
         {"id": "52027", "name": "Distribution Records (S13)"}, 
         {"id": "52052", "name": "Image - Incident"}, 
         {"id": "52053", "name": "Image - Location"}, 
         {"id": "52054", "name": "Image - Product"}, 
         {"id": "52055", "name": "Import Information"}, 
         {"id": "52056", "name": "Incident Report - Consumer"}, 
         {"id": "52057", "name": "Incident Report - Industry"}, 
         {"id": "52060", "name": "Label - Marketplace"}, 
         {"id": "52061", "name": "Label - Text"}, 
         {"id": "52020", "name": "Product Advertisement"}, 
         {"id": "52069", "name": "Product Specifications"}, 
         {"id": "52070", "name": "Proof of Accreditation"}, 
         {"id": "52071", "name": "Proof of Certification"}, 
         {"id": "52072", "name": "Proof of Standards Compliance"}, 
         {"id": "52074", "name": "Recall - Foreign"}, 
         {"id": "52086", "name": "Storage Information"}, 
         {"id": "52087", "name": "Test data"}, 
         {"id": "52088", "name": "Transport Information"}, 
         {"id": "52089", "name": "Other Documents"} 
];